dubbo:
  application:
    name: view-facade
  registry:
    address: zookeeper://192.168.140.129:2181
  protocol:
    port: 20882
server:
  port: 9099
spring:
  redis:
    host: 192.168.140.129
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 4
    cluster:
      nodes: 192.168.140.129:7001,192.168.140.129:7002,192.168.140.129:7003
